'use client'
import {useState,useRef} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {toast} from 'sonner'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Label} from '@/components/ui/label'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog'
import {ReceiptFilePicker} from '@/components/receipts/ReceiptFilePicker'
import {pendingByUser,todayInItaly,type Reimbursement,type StaffOption} from '@/lib/reimbursements/model'
import {getCurrentAnnoScout} from '@/lib/utils/payment'
import {WORKING_YEAR_COOKIE} from '@/lib/utils/workingYear'
import {submitReimbursement} from '@/lib/reimbursements/client'
const money=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n)
const dateLabel=(date:string)=>date.split('-').reverse().join('/')
const nativeSelect='h-11 w-full rounded-lg border bg-white px-3 text-base'
export default function ReimbursementsClient({year,userId,canValidate,initialRequests,users,categories}:{year:string;userId:string;canValidate:boolean;initialRequests:Reimbursement[];users:StaffOption[];categories:string[]}){
 const router=useRouter(),busyRef=useRef(false)
 const [rows,setRows]=useState(initialRequests),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[filter,setFilter]=useState('DA_RIMBORSARE'),[yearFilter,setYearFilter]=useState('ALL')
 const empty=()=>({id:crypto.randomUUID(),date:todayInItaly()>=`${year.slice(0,4)}-10-01`&&todayInItaly()<=`${year.slice(5)}-09-30`?todayInItaly():`${year.slice(5)}-09-30`,amount:'',category:categories[0]||'Altro',period:'ANNO',note:'',beneficiary:userId})
 const [form,setForm]=useState<ReturnType<typeof empty>|null>(null),[file,setFile]=useState<File|null>(null),[action,setAction]=useState<{row:Reimbursement;type:'confirm'|'cancel'}|null>(null),[paymentDate,setPaymentDate]=useState(todayInItaly()),[method,setMethod]=useState('Contanti')
 const refresh=async()=>{const response=await fetch('/api/rimborsi',{cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error||'Impossibile aggiornare l’elenco');setRows(result.requests);router.refresh()}
 const call=async(callback:()=>Promise<void>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);try{await callback()}catch(e){toast.error(e instanceof Error?e.message:'Operazione non riuscita')}finally{busyRef.current=false;setBusy(false)}}
 const submit=(event:React.FormEvent)=>{event.preventDefault();if(!form)return;void call(async()=>{
  await submitReimbursement({...form,year},file);setOpen(false);setForm(null);setFile(null);toast.success('Spesa inviata al tesoriere e admin come da rimborsare. Cassa invariata.');try{await refresh()}catch{toast.warning('Richiesta salvata. Ricarica la pagina per aggiornare l’elenco.')}
 })}
 const runAction=()=>{if(!action)return;void call(async()=>{const response=await fetch(`/api/rimborsi/${action.row.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:action.type,confirm:true,date:paymentDate,method})});const result=await response.json();if(!response.ok)throw Error(result.error||'Operazione non riuscita');setAction(null);toast.success(action.type==='confirm'?'Rimborso confermato e uscita registrata in cassa':'Richiesta annullata. Cassa invariata.');try{await refresh()}catch{toast.warning('Operazione salvata. Ricarica la pagina per aggiornare l’elenco.')}})}
 const summary=pendingByUser(rows),visible=rows.filter(r=>(filter==='ALL'||r.stato===filter)&&(yearFilter==='ALL'||r.anno_scout===yearFilter)),years=[...new Set([year,...rows.map(r=>r.anno_scout)])].sort().reverse()
 return <div className="mx-auto max-w-6xl space-y-4 p-3 md:p-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/cassa" className="text-sm underline">← Cassa e spese</Link><h1 className="mt-2 text-xl font-bold md:text-2xl">Spese anticipate e rimborsi</h1><p className="mt-1 text-sm text-muted-foreground">Le richieste da rimborsare non modificano saldi e spese totali. {canValidate?'Conferma solo i rimborsi già effettuati.':'Tesoriere e admin possono confermare il rimborso.'}</p></div><Button onClick={()=>{setForm(empty());setFile(null);setOpen(true)}}>Nuova spesa anticipata</Button></div>
  <section aria-label="Rimborsi dovuti per utente" className="rounded-xl border bg-amber-50 p-4"><h2 className="font-semibold">Da rimborsare · tutti gli anni</h2><p className="mt-1 text-lg font-bold">{money(summary.reduce((n,r)=>n+r.amount,0))}</p>{summary.length?<ul className="mt-3 space-y-2">{summary.map(r=><li key={r.id} className="flex justify-between gap-3 text-sm"><span>{r.name} · {r.count} {r.count===1?'spesa':'spese'}</span><strong>{money(r.amount)}</strong></li>)}</ul>:<p className="mt-2 text-sm">Nessun rimborso in attesa.</p>}{!canValidate&&<p className="mt-2 text-xs text-muted-foreground">Vedi le richieste inserite da te o intestate a te.</p>}</section>
  <div className="grid grid-cols-2 gap-3"><div><Label htmlFor="reimbursement-status">Stato</Label><select id="reimbursement-status" className={nativeSelect} value={filter} onChange={e=>setFilter(e.target.value)}><option value="DA_RIMBORSARE">Da rimborsare</option><option value="RIMBORSATO">Rimborsate</option><option value="ANNULLATO">Annullate</option><option value="ALL">Tutte</option></select></div><div><Label htmlFor="reimbursement-year">Anno della spesa</Label><select id="reimbursement-year" className={nativeSelect} value={yearFilter} onChange={e=>setYearFilter(e.target.value)}><option value="ALL">Tutti gli anni</option>{years.map(y=><option key={y}>{y}</option>)}</select></div></div>
  <div className="space-y-3">{visible.map(row=><article key={row.id} className="space-y-3 rounded-xl border bg-white p-4"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{row.categoria} · {row.beneficiary_name}</h2><p className="text-xs text-muted-foreground">Spesa del {dateLabel(row.data_spesa)} · {row.anno_scout} · {row.momento_anno}</p></div><strong className="whitespace-nowrap">{money(row.importo)}</strong></div><p className="text-sm">{row.stato==='DA_RIMBORSARE'?'Da rimborsare':row.stato==='RIMBORSATO'?'Rimborsata':'Annullata'} · Inserita da {row.created_by_name}</p>{row.note&&<p className="whitespace-pre-wrap break-words text-sm">{row.note}</p>}{row.stato==='RIMBORSATO'&&<p className="text-sm text-emerald-800">Restituita il {dateLabel(row.data_rimborso!)} · {row.metodo_rimborso} · Confermata da {row.validated_by_name}{row.movimento_id&&<> · <a className="underline" href="/cassa" onClick={()=>{document.cookie=`${WORKING_YEAR_COOKIE}=${getCurrentAnnoScout(new Date(`${row.data_rimborso}T12:00:00`))}; Path=/; Max-Age=31536000; SameSite=Lax; Secure`}}>Cassa {getCurrentAnnoScout(new Date(`${row.data_rimborso}T12:00:00`))}</a></>}</p>}<div className="flex flex-wrap gap-2">{row.file_name&&<a className="rounded-lg border px-3 py-2 text-sm" href={`/api/rimborsi/${row.id}/file`}>Scarica scontrino / file</a>}{row.stato==='DA_RIMBORSARE'&&<>{canValidate&&<Button size="sm" disabled={busy} onClick={()=>{setPaymentDate(todayInItaly());setMethod('Contanti');setAction({row,type:'confirm'})}}>Conferma rimborso</Button>}{(canValidate||row.created_by===userId)&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setAction({row,type:'cancel'})}>Annulla richiesta</Button>}</>}</div></article>)}{!visible.length&&<p className="py-6 text-center text-sm text-muted-foreground">Nessuna richiesta per questi filtri.</p>}</div>
  <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Nuova spesa anticipata</DialogTitle><DialogDescription>Anno {year}. Il tesoriere e admin vedranno la richiesta. Nessuna uscita viene contabilizzata ora.</DialogDescription></DialogHeader>{form&&<form onSubmit={submit}><fieldset disabled={busy} className="space-y-3"><div><Label htmlFor="refund-beneficiary">Da restituire a</Label><select id="refund-beneficiary" className={nativeSelect} value={form.beneficiary} onChange={e=>setForm({...form,beneficiary:e.target.value})}>{users.map(u=><option key={u.id} value={u.id}>{u.name}{u.id===userId?' (io)':''}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><Label htmlFor="advance-date">Data spesa</Label><Input id="advance-date" className="text-base" type="date" min={`${year.slice(0,4)}-10-01`} max={todayInItaly()<`${year.slice(5)}-09-30`?todayInItaly():`${year.slice(5)}-09-30`} required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div><div><Label htmlFor="advance-amount">Importo (€)</Label><Input id="advance-amount" className="text-base" type="number" inputMode="decimal" step="0.01" min="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div></div><div><Label htmlFor="advance-category">Categoria</Label><Input id="advance-category" className="text-base" list="refund-categories" required maxLength={150} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><datalist id="refund-categories">{categories.map(c=><option key={c} value={c}/>)}</datalist></div><div><Label htmlFor="advance-period">Momento anno</Label><select id="advance-period" className={nativeSelect} value={form.period} onChange={e=>setForm({...form,period:e.target.value})}><option value="ANNO">Anno</option><option value="CI">Campo invernale</option><option value="CE">Campo estivo</option></select></div><div><Label htmlFor="advance-note">Motivo / note</Label><Input id="advance-note" className="text-base" maxLength={2000} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></div><ReceiptFilePicker file={file} onChange={setFile} disabled={busy} description="Foto fino a 20 MB, ridotte prima dell’invio. PDF e altri documenti: massimo 3 MB."/><Button className="w-full" type="submit">{busy?'Salvataggio…':'Invia richiesta di rimborso'}</Button></fieldset></form>}</DialogContent></Dialog>
  <Dialog open={!!action} onOpenChange={v=>{if(!v&&!busy)setAction(null)}}><DialogContent><DialogHeader><DialogTitle>{action?.type==='confirm'?'Conferma rimborso effettuato':'Annulla richiesta'}</DialogTitle><DialogDescription>{action?.row.beneficiary_name} · {money(action?.row.importo||0)}. {action?.type==='confirm'?'Questa conferma registra l’uscita in cassa.':'La richiesta resterà archiviata e non entrerà in cassa.'}</DialogDescription></DialogHeader>{action?.type==='confirm'&&<div className="space-y-3"><div><Label htmlFor="refund-date">Data effettiva della restituzione</Label><Input id="refund-date" type="date" className="text-base" min={action.row.data_spesa} max={todayInItaly()} value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></div><div><Label htmlFor="refund-method">Metodo usato dal reparto</Label><select id="refund-method" className={nativeSelect} value={method} onChange={e=>setMethod(e.target.value)}><option>Contanti</option><option>Bonifico</option><option>Carta</option></select></div><p className="text-sm">La spesa verrà contabilizzata nell’anno della data indicata, anche se diverso dall’anno della spesa originale.</p></div>}<Button disabled={busy} onClick={runAction}>{busy?'Salvataggio…':action?.type==='confirm'?'Confermo: denaro restituito':'Conferma annullamento'}</Button></DialogContent></Dialog>
 </div>
}
