'use client'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { euros,italianDate,type Movement } from '@/lib/issuedReceipts/model'
import { type Proof,type ProofReading } from '@/lib/issuedReceipts/proof'
import type { Boy } from '@/lib/roster'
import { toast } from 'sonner'
const field='block w-full rounded-lg border p-2 text-base'
export default function ProofsPanel({movements,boys,proofs,reload}:{movements:Movement[];boys:Boy[];proofs:Proof[];reload:()=>Promise<void>}){
 const [boyId,setBoyId]=useState('all'),[missing,setMissing]=useState(true),[ids,setIds]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[reading,setReading]=useState<ProofReading|null>(null),[parent,setParent]=useState(1),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false)
 const bank=movements.filter(m=>m.tipo_movimento==='ENTRATA'&&m.importo>0&&m.ragazzo_id&&['bonifico','banca','bonifici'].includes(m.metodo?.toLowerCase()||''))
 const visible=bank.filter(m=>(boyId==='all'||m.ragazzo_id===boyId)&&(!missing||!proofs.some(p=>p.movimento_id===m.id&&p.confirmed)))
 const selected=bank.filter(m=>ids.includes(m.id));const boy=boys.find(b=>b.id===selected[0]?.ragazzo_id);const total=selected.reduce((n,m)=>n+m.importo,0)
 async function run(action:'analyze'|'save'){setBusy(true);try{if(!file)throw Error('Carica il documento');const fd=new FormData();fd.set('file',file);fd.set('ids',JSON.stringify(ids));fd.set('action',action);if(action==='save'){fd.set('confirm',String(confirmed));fd.set('parent',String(parent));fd.set('payer',reading?.payer||'');fd.set('amount',String(reading?.amount||0));fd.set('date',reading?.date||'')}
 const r=await fetch('/api/ricevute/prove',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw Error(j.error);if(action==='analyze'){setReading(j.reading);setParent(j.reading.suggestedParent||1);if(j.reading.warning)toast.info(j.reading.warning)}else{toast.success('Prova di bonifico archiviata e pagatore confermato');setIds([]);setFile(null);setReading(null);setConfirmed(false);await reload()}}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <section className="space-y-4"><h2 className="font-bold text-lg">Prove di bonifico e pagatori</h2><p className="text-sm text-slate-600">{bank.filter(m=>!proofs.some(p=>p.movimento_id===m.id&&p.confirmed)).length} bonifici senza prova confermata. Un documento può coprire più movimenti dello stesso ragazzo: selezionali e controlla il totale.</p><p className="text-xs text-slate-500">La lettura automatica usa i servizi OCR già configurati (Groq per foto, Google per PDF o riserva). Il documento resta in un archivio privato.</p>
 <label className="block text-sm">Ragazzo<select className={field} disabled={busy} value={boyId} onChange={e=>{setBoyId(e.target.value);setIds([]);setReading(null);setConfirmed(false)}}><option value="all">Tutti</option>{boys.map(b=><option key={b.id} value={b.id}>{b.nome} {b.cognome}</option>)}</select></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={missing} onChange={e=>setMissing(e.target.checked)}/>Mostra solo prove mancanti</label>
 <div className="rounded-xl border bg-white max-h-96 overflow-auto">{!visible.length&&<p className="p-3 text-sm">Nessun bonifico per questi filtri.</p>}{visible.map(m=>{const b=boys.find(b=>b.id===m.ragazzo_id),p=proofs.find(p=>p.movimento_id===m.id);return <div key={m.id} className="flex gap-3 p-3 border-b last:border-0"><input aria-label={`Seleziona bonifico ${m.numero_operazione}`} className="h-5 w-5 mt-1" type="checkbox" checked={ids.includes(m.id)} disabled={busy||!!selected.length&&selected[0].ragazzo_id!==m.ragazzo_id} onChange={e=>{setIds(v=>e.target.checked?[...v,m.id]:v.filter(id=>id!==m.id));setReading(null);setConfirmed(false)}}/><div className="flex-1 min-w-0 text-sm"><strong>{b?.nome} {b?.cognome} · {euros(m.importo)}</strong><p className="break-words">{italianDate(m.data!)} · {m.voce_spesa} · {m.note}</p>{p?<><p>Pagatore: {p.payer} · Genitore {p.parent} · {p.confirmed?'Prova confermata':'Movimento modificato: prova da verificare'}</p><a className="underline text-primary" href={`/api/ricevute/prove?movement=${m.id}`}>Scarica {p.filename}</a></>:<p className="text-amber-700">Prova non ricevuta</p>}</div></div>})}</div>
 {!!ids.length&&<div className="rounded-xl border bg-white p-4 space-y-3"><p className="font-bold">{boy?.nome} {boy?.cognome} · {ids.length} movimenti · {euros(total)}</p><label className="block text-sm">Foto o PDF della ricevuta di bonifico<input className="block w-full mt-2 text-base" type="file" accept="image/jpeg,image/png,application/pdf" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setReading(null);setConfirmed(false)}}/></label><Button disabled={busy||!file} onClick={()=>run('analyze')}>{busy?'Operazione in corso…':'Leggi pagatore e importo'}</Button>
 {reading&&<><p className="text-sm">Stato letto: {reading.status||'non leggibile'} · Causale: {reading.reference||'non leggibile'}</p><label className="block text-sm">Pagatore letto<input className={field} value={reading.payer} onChange={e=>{setReading({...reading,payer:e.target.value});setConfirmed(false)}}/></label><label className="block text-sm">Genitore da associare<select className={field} value={parent} onChange={e=>{setParent(Number(e.target.value));setConfirmed(false)}}><option value={1}>{boy?.genitore_1_nome||'Genitore 1 (nome mancante)'}</option><option value={2}>{boy?.genitore_2_nome||'Genitore 2 (nome mancante)'}</option></select></label><p className="text-xs">{reading.suggestedParent?'Genitore riconosciuto dal nome: verifica la proposta.':'Nessuna corrispondenza univoca: scegli il genitore corretto.'}</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="text-sm">Importo bonifico<input type="number" step="0.01" className={field} value={reading.amount??''} onChange={e=>{setReading({...reading,amount:e.target.value?Number(e.target.value):null});setConfirmed(false)}}/></label><label className="text-sm">Data esecuzione<input type="date" className={field} value={reading.date||''} onChange={e=>{setReading({...reading,date:e.target.value||null});setConfirmed(false)}}/></label></div><label className="flex gap-2 text-sm"><input className="h-5 w-5 shrink-0" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Ho verificato il documento: il bonifico è eseguito, pagatore e importo corrispondono ai movimenti selezionati.</label><Button disabled={busy||!confirmed||!reading.payer||Math.round((reading.amount||0)*100)!==Math.round(total*100)} onClick={()=>run('save')}>Salva documento e conferma pagatore</Button></>}
 </div>}
 </section>
}
