'use client'
import NextImage from 'next/image'
import ProofsPanel from './ProofsPanel'
import type { Proof } from '@/lib/issuedReceipts/proof'
import { useEffect,useState,useCallback } from 'react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { euros,italianDate,type Movement,type IssuedReceipt,type ReceiptConfig } from '@/lib/issuedReceipts/model'
import type { Boy } from '@/lib/roster'
type Payload={proofs:Proof[];boys:Boy[];movements:Movement[];receipts:IssuedReceipt[];issuedIds:string[];deliveries:{ricevuta_id:string;stato:string;email:string}[]}
const inputClass='block w-full rounded-lg border bg-white px-3 py-2 text-base'
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Rome'}).format(new Date())
export default function ReceiptsClient({year,canSign,canConnect}:{year:string;canSign:boolean;canConnect:boolean}){
 const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('generate'),[busy,setBusy]=useState(false)
 const [boy,setBoy]=useState('all'),[category,setCategory]=useState('all'),[parent,setParent]=useState(1),[date,setDate]=useState(today),[selected,setSelected]=useState<string[]>([]),[archiveSelected,setArchiveSelected]=useState<string[]>([])
 const [config,setConfig]=useState<ReceiptConfig>({treasurer:'',signature:''}),[gmail,setGmail]=useState({gmailConnected:false,gmailReady:false,sender:''}),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState<string[]>([]),[preview,setPreview]=useState(''),[sendReview,setSendReview]=useState(false)
 const load=useCallback(async()=>{try{const [r,c]=await Promise.all([fetch(`/api/ricevute?year=${year}`),fetch('/api/ricevute/config')]);const [j,k]=await Promise.all([r.json(),c.json()]);if(!r.ok||!c.ok)throw Error(j.error||k.error);setData(j);setConfig(k.config);setGmail(k);setError('')}catch(e){setError((e as Error).message)}},[year])
 useEffect(()=>{void load()},[load]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview])
 const eligible=data?.movements.filter(m=>!m.anticipo_capi_id&&m.tipo_movimento==='ENTRATA'&&m.importo>0&&m.ragazzo_id&&!data.issuedIds.includes(m.id))||[]
 const filtered=eligible.filter(m=>(boy==='all'||m.ragazzo_id===boy)&&(category==='all'||m.voce_spesa===category))
 const groups=(data?.boys||[]).flatMap(b=>[1,2].map(p=>({boy:b,parent:p,lines:eligible.filter(m=>m.ragazzo_id===b.id&&selected.includes(m.id)&&(data?.proofs.find(proof=>proof.movimento_id===m.id&&proof.confirmed)?.parent||parent)===p)}))).filter(g=>g.lines.length)
 const payer=(b:Boy,p:number)=>p===1?{name:b.genitore_1_nome,cf:b.genitore_1_codice_fiscale,email:b.genitore_1_email}:{name:b.genitore_2_nome,cf:b.genitore_2_codice_fiscale,email:b.genitore_2_email}
 const body=(g:typeof groups[number])=>({boyId:g.boy.id,ids:g.lines.map(m=>m.id),year,parent:g.parent,date})
 async function showPreview(g:typeof groups[number]){setBusy(true);try{const r=await fetch('/api/ricevute/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body(g))});if(!r.ok)throw Error((await r.json()).error);setPreview(URL.createObjectURL(await r.blob()))}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function issue(){setBusy(true);const messages:string[]=[];const done:string[]=[];for(const g of groups){try{const r=await fetch('/api/ricevute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body(g))});const j=await r.json();if(!r.ok)throw Error(j.error);messages.push(`${g.boy.nome} ${g.boy.cognome}: ricevuta ${j.receipt.numero}/${j.receipt.anno} archiviata`);done.push(...g.lines.map(l=>l.id))}catch(e){messages.push(`${g.boy.nome} ${g.boy.cognome}: ${(e as Error).message}`)}}setResult(messages);setSelected(ids=>ids.filter(id=>!done.includes(id)));setConfirmed(false);await load();setBusy(false)}
 async function signature(file:File){try{if(!['image/png','image/jpeg'].includes(file.type)||file.size>5000000)throw Error('Scegli una firma PNG o JPEG, massimo 5 MB');const url=URL.createObjectURL(file);const img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(Error('Immagine non leggibile'));img.src=url});URL.revokeObjectURL(url);const scale=Math.min(1,1000/img.width,600/img.height);const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);const signature=canvas.toDataURL('image/png');if(signature.length>700000)throw Error('Firma troppo grande: ritaglia lo spazio vuoto');setConfig(c=>({...c,signature}))}catch(e){toast.error((e as Error).message)}}
 async function saveSignature(){setBusy(true);try{const r=await fetch('/api/ricevute/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});const j=await r.json();if(!r.ok)throw Error(j.error);toast.success('Firma salvata: le ricevute già emesse restano invariate')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 const selectedReceipts=data?.receipts.filter(r=>archiveSelected.includes(r.id))||[]
 async function send(){setBusy(true);const messages:string[]=[];for(const r of selectedReceipts){try{const res=await fetch(`/api/ricevute/${r.id}/send`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true,expectedEmail:r.recipient?.email??r.snapshot.payer.email})});const j=await res.json();if(!res.ok)throw Error(j.error);messages.push(`Ricevuta ${r.numero}: inviata a ${(r.recipient?.email??r.snapshot.payer.email)}`)}catch(e){messages.push(`Ricevuta ${r.numero}: ${(e as Error).message}`)}}setResult(messages);setSendReview(false);setArchiveSelected([]);await load();setBusy(false)}
 async function share(r:IssuedReceipt){setBusy(true);try{const res=await fetch(`/api/ricevute/${r.id}/pdf`);if(!res.ok)throw Error('PDF non disponibile');const file=new File([await res.blob()],`ricevuta-${r.numero}-${r.anno}.pdf`,{type:'application/pdf'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:`Ricevuta ${r.numero}`,text:`Ricevuta pagamenti per ${r.snapshot.boy.name}`})}else{const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast.success('PDF scaricato. Apri WhatsApp del genitore e allegalo.')}}catch(e){if((e as Error).name!=='AbortError')toast.error((e as Error).message)}finally{setBusy(false)}}
 const pending=selectedReceipts.some(r=>data?.deliveries.some(d=>d.ricevuta_id===r.id&&d.stato!=='failed'))
 return <div className="mx-auto max-w-5xl p-3 sm:p-6 space-y-4"><header><h1 className="text-2xl font-bold">Ricevute pagamenti</h1><p className="text-sm text-slate-600">Anno scout {year.replace('-','/')} · Una ricevuta per ragazzo, pagatore e gruppo di movimenti scelti.</p></header>
 <div className="flex flex-wrap gap-2" role="tablist" aria-label="Ricevute">{[['generate','Genera'],['archive','Archivio'],['proofs','Prove bonifico'],['config','Firma e invio']].map(([key,label])=><Button key={key} role="tab" aria-selected={tab===key} variant={tab===key?'default':'outline'} onClick={()=>{setTab(key);setSendReview(false)}}>{label}</Button>)}</div>
 {error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3">{error}<Button className="ml-2" variant="outline" onClick={load}>Riprova</Button></div>}
 {!data&&!error&&<p>Caricamento…</p>}
 {tab==='config'&&<section className="rounded-xl border bg-white p-4 space-y-4"><h2 className="text-lg font-bold">Tesoriere e firma</h2><p className="text-sm">Carica la firma in immagine. Puoi sostituirla: ogni ricevuta emessa conserva la firma usata all’emissione.</p><label className="block text-sm">Nome e cognome del tesoriere<input className={inputClass} disabled={!canSign||busy} value={config.treasurer} onChange={e=>setConfig({...config,treasurer:e.target.value})}/></label>{config.signature&&<NextImage width={400} height={150} unoptimized className="max-h-24 max-w-full rounded border bg-white p-2" src={config.signature} alt="Firma del tesoriere"/>}{canSign?<><input aria-label="Carica o sostituisci firma" className="w-full text-base" disabled={busy} type="file" accept="image/png,image/jpeg" onChange={e=>{if(e.target.files?.[0])void signature(e.target.files[0]);e.target.value=''}}/><Button disabled={busy||!config.signature||!config.treasurer.trim()} onClick={saveSignature}>Salva nome e firma</Button></>:<p className="text-sm">La firma è gestita da ADMIN, CAPO UNITÀ o TESORIERE DI UNITÀ.</p>}
 <div className="border-t pt-4 space-y-2"><h2 className="text-lg font-bold">Invio email</h2><p className="text-sm">Mittente: {gmail.sender||'repartoeirenebrownsea.prato6@gmail.com'}</p><p className="text-sm">{gmail.gmailConnected?'Gmail collegato. Puoi inviare i PDF ai genitori dall’archivio.':gmail.gmailReady?'Collega Gmail per inviare le ricevute con PDF allegato.':'Invio diretto da attivare: manca la configurazione Google del progetto. Puoi già scaricare e condividere i PDF.'}</p>{canConnect&&gmail.gmailReady&&<a className="inline-block rounded-lg bg-primary px-4 py-2 text-white" href="/api/ricevute/gmail/connect">{gmail.gmailConnected?'Ricollega Gmail':'Collega Gmail'}</a>}<p className="text-xs text-slate-500">L’app richiede il permesso di inviare email. WhatsApp richiede la tua conferma nella chat o nel menu di condivisione del telefono.</p></div></section>}
 {tab==='proofs'&&data&&<ProofsPanel movements={data.movements} boys={data.boys} proofs={data.proofs} reload={load}/>}
 {tab==='generate'&&data&&<><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 rounded-xl border bg-white p-4"><label className="text-sm">Ragazzo<select className={inputClass} value={boy} onChange={e=>setBoy(e.target.value)}><option value="all">Tutti i ragazzi</option>{data.boys.map(b=><option key={b.id} value={b.id}>{b.nome} {b.cognome}{b.attivo===false?' (archiviato)':''}</option>)}</select></label><label className="text-sm">Voce di entrata<select className={inputClass} value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Tutte le voci</option>{[...new Set(eligible.map(m=>m.voce_spesa||''))].map(c=><option key={c} value={c}>{c||'Senza categoria'}</option>)}</select></label><label className="text-sm">Pagatore per movimenti senza prova confermata<select className={inputClass} value={parent} onChange={e=>{setParent(Number(e.target.value));setConfirmed(false)}}><option value={1}>Genitore 1</option><option value={2}>Genitore 2</option></select></label><label className="text-sm">Data emissione<input type="date" className={inputClass} value={date} onChange={e=>{setDate(e.target.value);setConfirmed(false)}}/></label></div>
 <p className="text-sm text-slate-600">Il pagatore viene scelto automaticamente dalle prove di bonifico confermate. Per altri pagamenti usa la scelta del genitore. Sono disponibili solo entrate positive collegate al ragazzo e non ancora certificate. Il censimento può essere incluso anche se escluso dal totale delle entrate.</p>
 {!!data.movements.filter(m=>!m.anticipo_capi_id&&m.tipo_movimento==='ENTRATA'&&m.importo>0&&!m.ragazzo_id).length&&<p className="rounded-lg bg-amber-50 p-3 text-sm">Ci sono entrate senza ragazzo collegato. Associale al ragazzo in Cassa prima di generare la ricevuta.</p>}
 <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy||!filtered.length} onClick={()=>{setSelected(ids=>[...new Set([...ids,...filtered.map(m=>m.id)])]);setConfirmed(false)}}>Seleziona i movimenti visibili</Button><Button variant="outline" disabled={busy} onClick={()=>{setSelected([]);setConfirmed(false)}}>Svuota selezione</Button></div>
 <div className="max-h-96 overflow-auto rounded-xl border bg-white">{!filtered.length&&<p className="p-4 text-sm">Nessun pagamento disponibile per questi filtri.</p>}{filtered.map(m=>{const b=data.boys.find(b=>b.id===m.ragazzo_id);return <label key={m.id} className="flex items-start gap-3 border-b last:border-0 p-3"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" disabled={busy} checked={selected.includes(m.id)} onChange={e=>{setSelected(ids=>e.target.checked?[...ids,m.id]:ids.filter(id=>id!==m.id));setConfirmed(false)}}/><span className="min-w-0 flex-1 text-sm"><strong>{b?.nome} {b?.cognome}</strong><span className="block break-words text-slate-600">{italianDate(m.data!)} · {m.voce_spesa} · {m.momento_anno} · {m.metodo}</span>{m.note&&<span className="block break-words text-xs">{m.note}</span>}</span><strong className="shrink-0 text-sm">{euros(m.importo)}</strong></label>})}</div>
 {!!groups.length&&<section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-bold">Controlla {groups.length} ricevut{groups.length===1?'a':'e'} prima di emettere</h2>{groups.map(g=><div key={`${g.boy.id}-${g.parent}`} className="border-b pb-3 text-sm space-y-1"><strong>{g.boy.nome} {g.boy.cognome} · {euros(g.lines.reduce((n,m)=>n+m.importo,0))} · {g.lines.length} movimenti</strong><p>CF ragazzo: {g.boy.codice_fiscale||'MANCANTE'}</p><p>Pagatore: {payer(g.boy,g.parent).name||'MANCANTE'} · CF: {payer(g.boy,g.parent).cf||'MANCANTE'}</p><p>Email: {payer(g.boy,g.parent).email||'non presente'}</p><Button variant="outline" disabled={busy} onClick={()=>showPreview(g)}>Anteprima PDF</Button></div>)}<label className="flex gap-2 text-sm"><input className="h-5 w-5 shrink-0" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confermo che il genitore indicato ha effettuato tutti i pagamenti selezionati e che i dati sono corretti.</label><Button disabled={busy||!confirmed} onClick={issue}>{busy?'Operazione in corso…':`Emetti e archivia ${groups.length} ricevut${groups.length===1?'a':'e'}`}</Button><p className="text-xs text-slate-500">La numerazione viene assegnata all’emissione. Per pagatori diversi, seleziona separatamente i rispettivi movimenti.</p></section>}
 {preview&&<div className="rounded-xl border bg-white p-3 space-y-2"><a className="text-primary underline" href={preview} target="_blank" rel="noreferrer">Apri anteprima PDF</a><iframe title="Anteprima ricevuta" className="hidden sm:block h-[620px] w-full" src={preview}/></div>}
 </>}
 {tab==='archive'&&data&&<><p className="text-sm text-slate-600">{data.receipts.length} ricevute archiviate. Le modifiche successive a Cassa, anagrafiche e firma non cambiano queste ricevute.</p><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>{setArchiveSelected(data.receipts.filter(r=>(r.recipient?.email??r.snapshot.payer.email)&&!data.deliveries.some(d=>d.ricevuta_id===r.id&&d.stato!=='failed')).map(r=>r.id));setSendReview(false)}}>Seleziona tutte da inviare via email</Button><Button disabled={busy||!archiveSelected.length||!gmail.gmailConnected||pending} onClick={()=>setSendReview(true)}>Prepara invio email ({archiveSelected.length})</Button></div>{!gmail.gmailConnected&&<p className="text-sm">Collega Gmail in “Firma e invio” per inviare direttamente.</p>}
 {sendReview&&<section className="rounded-xl border bg-blue-50 p-4 space-y-3"><h2 className="font-bold">Conferma destinatari e documenti</h2>{selectedReceipts.map(r=><p key={r.id} className="break-words text-sm">Ricevuta {r.numero}/{r.anno} · {r.snapshot.boy.name} → {(r.recipient?.email??r.snapshot.payer.email)||'EMAIL MANCANTE'}</p>)}<Button disabled={busy||pending||selectedReceipts.some(r=>!(r.recipient?.email??r.snapshot.payer.email))} onClick={send}>Invia le email con PDF allegato</Button></section>}
 {data.receipts.map(r=>{const delivery=data.deliveries.find(d=>d.ricevuta_id===r.id);const phone=(r.recipient?.phone??r.snapshot.payer.phone).replace(/[^0-9]/g,'');const wa=phone.startsWith('39')?phone:`39${phone}`;return <article key={r.id} className="rounded-xl border bg-white p-4 space-y-3"><div className="flex gap-3 items-start"><input aria-label={`Seleziona ricevuta ${r.numero}`} className="h-5 w-5 mt-1" type="checkbox" disabled={busy||!!delivery&&delivery.stato!=='failed'} checked={archiveSelected.includes(r.id)} onChange={e=>{setArchiveSelected(ids=>e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id));setSendReview(false)}}/><div className="min-w-0 flex-1"><h2 className="font-bold">N. {r.numero}/{r.anno} · {r.snapshot.boy.name}</h2><p className="text-sm break-words">{r.snapshot.payer.name} · {euros(r.snapshot.total)} · {italianDate(r.snapshot.date)}</p><p className="text-sm break-words">{(r.recipient?.email??r.snapshot.payer.email)||'Email non presente'}{delivery?` · ${{sent:'Inviata',sending:'Invio in corso: verifica Gmail',failed:'Invio rifiutato, riprovabile',uncertain:'Esito da verificare in Gmail'}[delivery.stato]||delivery.stato}`:''}</p></div></div><div className="flex flex-wrap gap-2"><a className="rounded-lg border px-3 py-2 text-sm" href={`/api/ricevute/${r.id}/pdf`}>Scarica PDF</a><Button variant="outline" disabled={busy} onClick={()=>share(r)}>Condividi PDF</Button>{phone&&<a className="rounded-lg border px-3 py-2 text-sm" target="_blank" rel="noreferrer" href={`https://wa.me/${wa}?text=${encodeURIComponent(`Ciao ${r.snapshot.payer.name}, ti invio la ricevuta n. ${r.numero}/${r.anno} per ${r.snapshot.boy.name}.`)}`}>Apri WhatsApp del genitore</a>}</div><p className="text-xs text-slate-500">Su WhatsApp allega il PDF scaricato oppure scegli WhatsApp da “Condividi PDF”.</p></article>})}</>}
 {!!result.length&&<section role="status" className="rounded-xl border bg-white p-4 space-y-2"><h2 className="font-bold">Esito operazioni</h2>{result.map((s,i)=><p key={i} className="text-sm break-words">{s}</p>)}</section>}
 </div>
}
