import 'server-only'
import {createAdminClient} from '@/lib/supabase/admin'
import {getStaffRole} from '@/lib/security/roles'
import {canReadReimbursement,canValidateReimbursement,type Reimbursement,type StaffOption} from './model'
import type {User} from '@supabase/supabase-js'
export async function freshUser(user:User){const {data,error}=await createAdminClient().auth.admin.getUserById(user.id);if(error||!data.user||!getStaffRole(data.user,process.env.ADMIN_EMAILS||''))throw Error('Account non abilitato');return data.user}
export async function staffOptions():Promise<StaffOption[]>{const rows:StaffOption[]=[];const db=createAdminClient();for(let page=1;;page++){const {data,error}=await db.auth.admin.listUsers({page,perPage:100});if(error)throw Error('Elenco utenti non disponibile');rows.push(...data.users.filter(u=>getStaffRole(u,process.env.ADMIN_EMAILS||'')).map(u=>({id:u.id,name:typeof u.user_metadata?.name==='string'&&u.user_metadata.name.trim()?u.user_metadata.name.trim():u.email||'Utente'})));if(data.users.length<100)return rows.sort((a,b)=>a.name.localeCompare(b.name,'it'))}}
export async function listRequests(user:User,year?:string){const db=createAdminClient();const rows:Reimbursement[]=[];const manager=canValidateReimbursement(user,process.env.ADMIN_EMAILS||'');for(let from=0;;from+=500){let query=db.from('rimborsi').select('id,created_by,created_by_name,beneficiary_id,beneficiary_name,anno_scout,data_spesa,importo,categoria,momento_anno,note,file_name,stato,movimento_id,data_rimborso,metodo_rimborso,validated_by_name,validated_at,created_at').order('created_at',{ascending:false}).order('id');if(year)query=query.eq('anno_scout',year);if(!manager)query=query.or(`created_by.eq.${user.id},beneficiary_id.eq.${user.id}`);const {data,error}=await query.range(from,from+499);if(error||!data)throw Error('Richieste di rimborso non disponibili');rows.push(...data as Reimbursement[]);if(data.length<500)return rows}}
export async function authorizedRequest(id:string,user:User,allowSettledFile=false){const {data,error}=await createAdminClient().from('rimborsi').select('*').eq('id',id).maybeSingle();if(error||!data)throw Error('Richiesta non disponibile');if(!canReadReimbursement(data,user.id,canValidateReimbursement(user,process.env.ADMIN_EMAILS||''))&&!(allowSettledFile&&data.stato==='RIMBORSATO'&&data.movimento_id))throw Error('Richiesta non disponibile');return data}
