'use client'
import { useState } from 'react'
import { toast } from 'sonner'
import { type RosterPreview } from '@/lib/roster'
import { Button } from '@/components/ui/button'
export default function RosterSettings(){
 const [rows,setRows]=useState<Record<string,unknown>[]>([]),[preview,setPreview]=useState<RosterPreview[]>([]),[mode,setMode]=useState('create'),[busy,setBusy]=useState(false),[url,setUrl]=useState('')
 async function read(file:File){setBusy(true);setPreview([]);try{if(file.size>5000000)throw Error('Massimo 5 MB');const {readRosterWorkbook}=await import('@/lib/rosterWorkbook');const data=readRosterWorkbook(await file.arrayBuffer());setRows(data);toast.success(`${data.length} righe lette: controlla l’anteprima`)}catch(e){setRows([]);toast.error((e as Error).message)}finally{setBusy(false)}}
 async function run(commit=false){setBusy(true);try{const r=await fetch('/api/roster',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows,mode,commit,googleUrl:!rows.length?url:undefined})});const j=await r.json();if(!r.ok)throw Error(j.error);if(commit){toast.success(`${j.count} anagrafiche importate, ${j.skipped} già presenti saltate`);setPreview([]);setRows([]);setUrl('')}else{setPreview(j.preview);if(j.rows)setRows(j.rows)}}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <section className="rounded-xl border bg-white p-4 space-y-4"><h2 className="text-xl font-bold">Importa ed esporta anagrafiche</h2><p className="text-sm text-slate-600">Modello compilabile in Excel o Google Sheets, con codici fiscali e contatti. L’esportazione include anche ragazzi archiviati, note sanitarie e stati dei documenti.</p>
 <div className="flex flex-wrap gap-2"><a className="rounded-md bg-primary px-3 py-2 text-sm text-white" href="/api/roster/template">Scarica modello Excel</a><a className="rounded-md border px-3 py-2 text-sm" href="/api/roster?format=xlsx">Esporta tutte le anagrafiche</a></div>
 <label className="block text-sm">Carica Excel o CSV<input className="block w-full mt-2 text-base" type="file" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e=>{if(e.target.files?.[0])void read(e.target.files[0]);e.target.value=''}}/></label>
 <label className="block text-sm">Oppure link Google Sheets (scheda ANAGRAFICA)<input className="block w-full rounded-md border p-2 text-base" value={url} onChange={e=>{setUrl(e.target.value);setRows([]);setPreview([])}} placeholder="https://docs.google.com/spreadsheets/d/..."/></label>
 <p className="text-xs text-slate-500">Per un foglio privato, scarica l’Excel e caricalo qui oppure condividilo con l’account di servizio già configurato. Non occorre renderlo pubblico.</p>
 <label className="block text-sm">Anagrafiche già presenti<select className="block w-full rounded-md border p-2 text-base" disabled={busy} value={mode} onChange={e=>{setMode(e.target.value);setPreview([])}}><option value="create">Crea nuovi ragazzi e salta quelli esistenti</option><option value="update">Aggiorna quelli esistenti e crea quelli nuovi</option></select></label>
 <Button disabled={busy||(!rows.length&&!url)} onClick={()=>run()}>Controlla anteprima</Button>
 {!!preview.length&&<><div className="max-h-72 overflow-auto rounded-md border"><table className="w-full text-sm"><thead><tr><th>Riga</th><th>Ragazzo</th><th>Azione</th><th>Verifica</th></tr></thead><tbody>{preview.map(r=><tr key={r.row} className="border-t"><td className="p-2">{r.row}</td><td>{String(r.data.nome)} {String(r.data.cognome)}</td><td>{{create:'Crea',update:'Aggiorna',skip:'Salta'}[r.action]}</td><td className={r.errors.length?'text-red-700':'text-green-700'}>{r.errors.join('; ')||'OK'}</td></tr>)}</tbody></table></div><p className="text-xs text-slate-500">Le celle vuote mantengono i dati esistenti. Gli errori annullano l’intera importazione.</p><Button disabled={busy||preview.some(r=>r.errors.length)} onClick={()=>run(true)}>Conferma importazione</Button></>}
 </section>
}
