import { validDate, validId, todayInItaly } from '@/lib/reimbursements/model'
import { dateInWorkingYear, validWorkingYear } from '@/lib/utils/workingYear'
export type StaffExpense={id:string;created_by:string;created_by_name:string;anno_scout:string;data_spesa:string;descrizione:string;importo:number;metodo:string;file_path:string|null;file_name:string|null;fingerprint:string;movimento_id:string|null;created_at:string}
export type StaffQuota={id:string;anticipo_id:string;staff_id:string;staff_name:string;quota:number}
export type StaffReturn={id:string;quota_id:string;importo:number;data:string;metodo:string;validated_by:string;validated_by_name:string;created_at:string;movimento_id:string}
export type StaffShare=StaffQuota & {restituito:number;residuo:number;expense:Omit<StaffExpense,'file_path'|'fingerprint'>;returns:StaffReturn[]}
export function cents(value:unknown){const number=Number(String(value??'').replace(',','.'));if(!Number.isFinite(number)||number<=0||number>1000000||Math.abs(number*100-Math.round(number*100))>0.00001)throw Error('Importo non valido: usa due decimali');return Math.round(number*100)}
export function splitEqually(total:number,ids:string[]){if(!ids.length||total<ids.length)throw Error('Importo insufficiente per le quote selezionate');const base=Math.floor(total/ids.length),extra=total%ids.length;return ids.map((id,i)=>({id,quota:(base+(i<extra?1:0))/100}))}
export function parseStaffExpense(input:Record<string,unknown>){const id=validId(input.id),year=validWorkingYear(typeof input.year==='string'?input.year:null),date=validDate(input.date),amount=cents(input.amount),description=String(input.description||'').trim(),method=String(input.method||'');if(!year||!dateInWorkingYear(date,year)||date>todayInItaly())throw Error('La data deve appartenere all’anno scelto e non essere futura');if(!description||description.length>2000||!['Contanti','Carta','Bonifico'].includes(method))throw Error('Completa descrizione e metodo della spesa');if(!Array.isArray(input.shares)||input.shares.length<1||input.shares.length>100)throw Error('Scegli i capi tra cui dividere la spesa');const shares=input.shares.map((row:{id?:unknown;quota?:unknown})=>({id:validId(row.id),quota:cents(row.quota)}));if(new Set(shares.map(s=>s.id)).size!==shares.length||shares.reduce((n,s)=>n+s.quota,0)!==amount)throw Error('Le quote devono essere distinte e sommare esattamente l’importo della spesa');return{id,year,date,amount,description,method,shares}}
export function staffFileUrl(pointer:string){const match=pointer.match(/^capo:([a-f0-9-]{36})\//i);return match?`/api/anticipi-capi/${match[1]}/file`:null}
